# Generated by Django 5.2.8 on 2025-12-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
