# Generated by Django 5.2.8 on 2025-12-08 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0004_remove_attendance_date_remove_attendance_on_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
