# Generated by Django 5.2.8 on 2025-12-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0005_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
