# Generated by Django 5.2.8 on 2025-12-10 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0006_attendance_overtime_hours_attendance_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='login_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
