# Generated by Django 5.2.8 on 2025-12-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0007_remove_loginhistory_ip_address_and_more'),
        ('employees', '0009_employee_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loginhistory',
            unique_together={('employee', 'login_date')},
        ),
    ]
