# Generated by Django 5.2.8 on 2025-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0008_alter_loginhistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
