# Generated by Django 5.2.8 on 2025-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0009_loginhistory_logout_time'),
        ('employees', '0009_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together={('employee', 'leave_date')},
        ),
    ]
