# Generated by Django 5.2.8 on 2025-12-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0010_alter_leave_reason_alter_leave_unique_together'),
        ('employees', '0009_employee_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
