# Generated by Django 5.2.8 on 2025-12-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0011_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
