# Generated by Django 5.2.8 on 2025-11-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_id_proofs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('license', 'Driving License')], max_length=20, null=True),
        ),
    ]
