# Generated by Django 5.2.8 on 2025-11-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_id_proof_document_employee_id_proof_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id_proof_number',
        ),
    ]
