# Generated by Django 5.2.8 on 2025-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_id_proof_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('intern', 'Intern')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('senior', 'Senior Developer'), ('junior', 'Junior Developer'), ('manager', 'Manager')], max_length=20, null=True),
        ),
    ]
