# Generated by Django 5.2.8 on 2025-12-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='employee_offer_letters/'),
        ),
    ]
