# Generated by Django 5.2.8 on 2026-01-13 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_offer_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('upi', 'UPI'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('hourly', 'Hourly'), ('contract', 'Contract')], max_length=20, null=True),
        ),
    ]
