# Generated by Django 5.2.8 on 2026-01-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_payment_method_employee_reporting_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('intern', 'Intern')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'employment_type': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, help_text='Job role like Developer, Team Lead, HR, Accountant', max_length=100, null=True),
        ),
    ]
