# Generated by Django 5.2.8 on 2026-01-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'employment_type': 'staff', 'is_manager': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employees.employee'),
        ),
    ]
