# Generated by Django 5.2.8 on 2026-01-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_is_manager_alter_employee_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee_resumes/'),
        ),
    ]
