# Generated by Django 5.2.8 on 2026-01-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('python', 'Python'), ('mern', 'MERN Stack'), ('uiux', 'UI/UX'), ('hr', 'HR'), ('flutter', 'Flutter'), ('software', 'Software Development'), ('tester', 'Software Testing'), ('data_analytics', 'Data Analytics'), ('devops', 'DevOps'), ('cybersecurity', 'Cyber Security')], max_length=20),
        ),
    ]
