# Generated by Django 5.2.8 on 2026-01-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('python', 'Python'), ('mern', 'MERN Stack'), ('uiux', 'UI/UX'), ('hr', 'HR'), ('flutter', 'Flutter'), ('software', 'Software Development'), ('tester', 'Software Testing'), ('data_analytics', 'Data Analytics'), ('devops', 'DevOps'), ('cybersecurity', 'Cyber Security'), ('digital_marketing', 'Digital Marketing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('license', 'Driving License'), ('pan', 'PAN Card'), ('passport', 'Passport')], max_length=20, null=True),
        ),
    ]
