# Generated by Django 5.2.8 on 2025-12-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('active_employees', models.IntegerField(default=0)),
                ('active_interns', models.IntegerField(default=0)),
                ('project_count', models.IntegerField(default=0)),
                ('attendance_percent', models.FloatField(default=0.0)),
            ],
        ),
    ]
