# Generated by Django 5.2.8 on 2026-01-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardSnapshot',
        ),
    ]
