# Generated by Django 5.2.8 on 2025-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_logo', models.ImageField(blank=True, null=True, upload_to='project_logos/')),
                ('project_name', models.CharField(max_length=255)),
                ('project_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('not_started', 'Not Started')], default='ongoing', max_length=20)),
                ('due_date', models.DateField()),
                ('project_type', models.CharField(choices=[('web', 'Web'), ('app', 'App'), ('webapp', 'WebApp')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_team', models.ManyToManyField(related_name='projects', to='employees.employee')),
            ],
        ),
    ]
