# Generated by Django 5.2.8 on 2025-12-17 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_password'),
        ('project', '0002_remove_project_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphase',
            name='project',
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='project_teams', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='project.project')),
            ],
        ),
        migrations.DeleteModel(
            name='PhaseTask',
        ),
        migrations.DeleteModel(
            name='ProjectPhase',
        ),
    ]
