# Generated by Django 5.2.8 on 2025-12-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_password'),
        ('project', '0003_remove_projectphase_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
