# Generated by Django 5.2.8 on 2025-12-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectphase_phaseemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphase',
            name='project',
        ),
        migrations.DeleteModel(
            name='PhaseEmployee',
        ),
        migrations.DeleteModel(
            name='ProjectPhase',
        ),
    ]
