# Generated by Django 5.2.8 on 2025-12-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_password'),
        ('project', '0006_remove_projectphase_project_delete_phaseemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='project.project')),
                ('project_teams', models.ManyToManyField(blank=True, related_name='planned_projects', to='employees.employee')),
            ],
        ),
    ]
