# Generated by Django 5.2.8 on 2026-01-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_offer_letter'),
        ('project', '0009_deploymentplanning_developmentplanning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentplanning',
            name='status',
        ),
        migrations.RemoveField(
            model_name='designplanning',
            name='status',
        ),
        migrations.RemoveField(
            model_name='developmentplanning',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projectplanning',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testingplanning',
            name='status',
        ),
        migrations.AlterField(
            model_name='deploymentplanning',
            name='project_teams',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='designplanning',
            name='project_teams',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='developmentplanning',
            name='project_teams',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='projectplanning',
            name='project_teams',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='testingplanning',
            name='project_teams',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
    ]
