# Generated by Django 5.2.8 on 2026-01-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_deploymentplanning_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
