# Generated by Django 5.2.8 on 2026-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='ProjectBudget',
        ),
    ]
