# Generated by Django 5.2.8 on 2026-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_remaining_amount_project_spent_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_contact',
            field=models.CharField(blank=True, help_text='Client phone number', max_length=15, null=True),
        ),
    ]
