# Generated by Django 5.2.8 on 2026-01-12 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_offer_letter'),
        ('project', '0013_project_client_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designplanning',
            name='project',
        ),
        migrations.RemoveField(
            model_name='designplanning',
            name='project_teams',
        ),
        migrations.RemoveField(
            model_name='developmentplanning',
            name='project',
        ),
        migrations.RemoveField(
            model_name='developmentplanning',
            name='project_teams',
        ),
        migrations.RemoveField(
            model_name='projectplanning',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectplanning',
            name='project_teams',
        ),
        migrations.RemoveField(
            model_name='testingplanning',
            name='project',
        ),
        migrations.RemoveField(
            model_name='testingplanning',
            name='project_teams',
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(choices=[('planning', 'Project Planning'), ('design', 'Design'), ('development', 'Development'), ('testing', 'Testing'), ('deployment', 'Deployment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='project.project')),
            ],
            options={
                'unique_together': {('project', 'phase_type')},
            },
        ),
        migrations.CreateModel(
            name='PhaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.projectphase')),
            ],
        ),
        migrations.DeleteModel(
            name='DeploymentPlanning',
        ),
        migrations.DeleteModel(
            name='DesignPlanning',
        ),
        migrations.DeleteModel(
            name='DevelopmentPlanning',
        ),
        migrations.DeleteModel(
            name='ProjectPlanning',
        ),
        migrations.DeleteModel(
            name='TestingPlanning',
        ),
    ]
