# Generated by Django 5.2.8 on 2026-01-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_offer_letter'),
        ('project', '0014_remove_designplanning_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
