# Generated by Django 5.2.8 on 2026-01-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_offer_letter'),
        ('project', '0015_projectphase_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphase',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='projectphase',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_phases', to='employees.employee'),
        ),
    ]
