# Generated by Django 5.2.8 on 2026-01-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_phasetask_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasetask',
            name='project',
        ),
    ]
