# Generated by Django 5.2.8 on 2026-01-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_phasetask_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
