# Generated by Django 5.2.8 on 2026-01-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_resume'),
        ('project', '0022_phasetask_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasetask',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='phasetask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='employees.employee'),
        ),
    ]
