# Generated by Django 5.2.8 on 2026-01-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_phasetask_assigned_to_phasetask_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetask',
            name='task_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='phase_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
