# Generated by Django 5.2.8 on 2026-01-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_resume'),
        ('project', '0024_phasetask_task_id_projectphase_phase_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectphase',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='phase_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.UniqueConstraint(fields=('project', 'phase_type'), name='unique_phase_per_project'),
        ),
    ]
