# Generated by Django 5.2.8 on 2026-01-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_alter_projectphase_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'Mobile App'), ('webapp', 'Web App'), ('desktop', 'Desktop App'), ('api', 'API'), ('software', 'Software')], max_length=20),
        ),
    ]
