# Generated by Django 5.2.8 on 2026-01-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_alter_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'Mobile App'), ('webapp', 'Web App'), ('desktop', 'Desktop App'), ('software', 'Software'), ('marketing', 'Marketing')], max_length=20),
        ),
    ]
