# Generated by Django 5.2.8 on 2025-11-28 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
